# Generated by Django 5.0.4 on 2024-04-23 15:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Degrees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the degree name', max_length=50, unique=True, verbose_name='Degree Name')),
                ('degree_type', models.CharField(choices=[('AD', 'Associate Degree'), ('BD', "Bachelor's Degree"), ('GD', 'Graduate Degree')], help_text='Select degree type', max_length=2, verbose_name='Degree Type')),
                ('total_credits', models.PositiveIntegerField(help_text='Insert degree total credits', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Total Credits to get')),
            ],
            options={
                'db_table': 'degrees',
                'ordering': ['id', 'name', 'degree_type'],
            },
        ),
    ]
