# Generated by Django 5.0.4 on 2024-04-23 15:50

import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter your first name', max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text='Enter your middle name', max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text='Enter your last name', max_length=50, verbose_name='Last Name')),
                ('address', models.TextField(help_text='Enter your address', max_length=254, verbose_name='Address')),
                ('birth_country', django_countries.fields.CountryField(help_text='Select your birth country', max_length=2)),
                ('email', models.EmailField(help_text='Enter your email', max_length=254, verbose_name='Email Address')),
                ('date_of_birth', models.DateField(help_text='Enter your birthdate')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Other')], help_text='Select your gender', max_length=1)),
                ('cellphone', phonenumber_field.modelfields.PhoneNumberField(help_text='Enter your phone number', max_length=128, region=None, unique=True)),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
