# Generated by Django 5.0.4 on 2024-04-23 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('degree', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Coures enrollment date')),
                ('status', models.CharField(choices=[('E', 'Enrolled'), ('C', 'Completed'), ('P', 'Pending'), ('F', 'Failed')], help_text='Select student status in the course', max_length=2, verbose_name='Course Status')),
                ('course_id', models.ForeignKey(help_text='Select Course Id', on_delete=django.db.models.deletion.CASCADE, to='courses.courses', verbose_name='Course id')),
                ('student_id', models.ForeignKey(help_text='Select Student Id', on_delete=django.db.models.deletion.CASCADE, to='students.students', verbose_name='Student id')),
            ],
            options={
                'db_table': 'course_enrollments',
                'ordering': ['enrollment_date', 'course_id', 'student_id'],
            },
        ),
        migrations.CreateModel(
            name='DegreeEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True, verbose_name='Degree enrollment date')),
                ('end_date', models.DateField(blank=True, help_text='Select the date where the student got the degree', null=True, verbose_name='Degree end date')),
                ('degree_id', models.ForeignKey(help_text='Select Degree Id', on_delete=django.db.models.deletion.CASCADE, to='degree.degrees', verbose_name='Degree id')),
                ('student_id', models.ForeignKey(help_text='Select Student Id', on_delete=django.db.models.deletion.CASCADE, to='students.students', verbose_name='Student id')),
            ],
            options={
                'db_table': 'degree_enrollments',
                'ordering': ['id', 'degree_id', 'student_id'],
            },
        ),
    ]
